name: Fly Deploy

on: [push]

env:
    FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
    deploy:
        name: Deploy app
        runs-on: ubuntu-latest
        if: "contains(github.event.head_commit.message, '(deploy)')"
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "18.x"
                  registry-url: "https://registry.npmjs.org"
            - run: yarn
            - run: yarn build
            - uses: superfly/flyctl-actions@1.1
              with:
                  args: "deploy"
